spring:
  datasource:
    url: jdbc:mysql://localhost:3306/red4java?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  messages:
    basename: messages/message
    encoding: UTF-8
  web:
    resources:
      chain:
        html-application-cache: true  # Enable HTML5 application cache manifest rewriting.
        enabled: true                 # Enable the Spring Resource Handling chain. Disabled by default unless at least one strategy has been enabled.
        strategy:
          content:
            enabled: true # Enable the content Version Strategy.
            paths: /**    # Comma-separated list of patterns to apply to the Version Strategy.
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/



