spring:
  datasource:
    url: jdbc:mysql://localhost:3306/red4java?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
